version: "3"

services:
  blackstrap:
    container_name: blackstrap
    image: ghcr.io/metabronx/blackstrap
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/New_York
    working_dir: /home/vpn-user/remote
    volumes:
      - ${FPDIR}/vpn-configs:/config
      - ${FPDIR}/ssh-jail:/root/.ssh
    networks:
      - blackstrap-internal
    ports:
      - 51820:51820/udp
      - 1111:22/tcp
    privileged: true
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE
      - SYS_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/fuse
    restart: unless-stopped

networks:
  blackstrap-internal:
