version: "3"

services:
  blackstrap:
    image: ghcr.io/metabronx/blackstrap
    environment:
      - TZ=America/New_York
    volumes:
      - ${FPDIR}/vpn-configs:/config
      - ${FPDIR}/client-ssh:/home/vpn-user/.ssh
      - ${MOUNT}:/home/vpn-user/remote
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/fuse
    restart: unless-stopped
