version: "3"

services:
  blackstrap:
    container_name: blackstrap_server
    image: ghcr.io/metabronx/blackstrap
    env_file: npeers
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/New_York
      - SERVERURL=auto
      - PEERDNS=1.1.1.1
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=false
    volumes:
      - ${FPDIR}/vpn-configs:/config
      # - ${FPDIR}/ssh-jail:/home/vpn-user
      - ${MOUNT}:/home/vpn-user/remote
    networks:
      - blackstrap-internal
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

networks:
  blackstrap-internal:
