[tool.poetry]
name = "sdcli"
version = "1.0.0"
description = "CLI scripts for automating important grunt work."
authors = ["Elias Gabriel <me@eliasfgabriel.com>"]

[tool.poetry.dependencies]
python = "^3.6"
typer = "^0.3.2"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
