[tool.poetry]
name = "sdcli"
version = "1.1.0"
description = "CLI scripts for automating important grunt work."
authors = ["Elias Gabriel <me@eliasfgabriel.com>"]

[tool.poetry.dependencies]
python = "^3.6.2"
typer = {extras = ["all"], version = "^0.3.2"}
aiohttp = {extras = ["speedups"], version = "^3.7.4"}

[tool.poetry.scripts]
sdcli = "sdcli.main:app"

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
show_column_numbers = true
follow_imports = "silent"
warn_unreachable = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
