services:
  s3fs:
    container_name: blackstrap_bridge_${AWS_S3_BUCKET}
    image: ghcr.io/metabronx/blackstrap-s3
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    networks:
      - blackstrap-s3-internal
    ports:
      - 1111:22/tcp
    environment:
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
    volumes:
      - ${SSH_PUBKEY}:/etc/ssh/host_pubkey

networks:
  blackstrap-s3-internal:
