name: CI

on: [push, pull_request]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        os: [
          macos-11, macos-12, macos-13,
          ubuntu-20.04, ubuntu-22.04,
          windows-2019, windows-2022
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Check styling and typing
        uses: pre-commit/action@v2.0.3  # last support for 3.7

  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        os: [
          macos-11, macos-12, macos-13,
          ubuntu-20.04, ubuntu-22.04,
          windows-2019, windows-2022
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install dependencies
        run: pdm install -G :all
      - name: Run tests
        run: pdm run pytest --cov=sdcli --cov-branch --cov-report=xml
      - name: Upload coverage metric
        if: ${{ matrix.os == 'ubuntu-22.04' && matrix.python-version == '3.7' }}
        env:
          AUTHKEY: ${{ secrets.OPENENDPOINT_CODECOV }}
        shell: bash
        run: |
          # the number after line-rate on the second line of the xml (overall score)
          export metric=$(\
            sed -nr '2,2s/.*line-rate="([[:digit:].]{1,5}).*/\1/p' coverage.xml)
          # convert the number to a percentage
          export metric=$(awk -vn=$metric 'BEGIN{printf("%.0f",n*100)}')
          # upload to openendpoint.tools
          curl \
            -H "Content-Type: application/json" \
            -d "{\"slug\":\"sdcli\",\"metric\":$metric,\"authkey\":\"$AUTHKEY\"}" \
            https://openendpoint.tools/metrics/generic
